build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank Loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
    onCallSupport:
      - (555) 555-1234
      - (555) 523-1345
  techSupport:
    name: ashraf
    email: "ashraf@test.com"
    phone: 123456		